const SHEETS={PIPELINE:'Content Pipeline',KANBAN:'Kanban Board',CALENDAR:'Content Calendar',CONFIG:'Config',PROMPTS:'Prompt Library'};
function onOpen(){SpreadsheetApp.getUi().createMenu('Marketing OS')
.addItem('Refresh Kanban','refreshKanbanBoard')
.addItem('Sync Pipeline to Calendar','syncPipelineToCalendar')
.addSeparator()
.addItem('Generate Blog Outline from Selected Pipeline Row','generateBlogOutlineFromSelectedRow')
.addItem('Generate Social Pack from Selected Pipeline Row','generateSocialPackFromSelectedRow')
.addItem('Generate GMB Post from Selected Calendar Row','generateGMBPostFromSelectedRow')
.addSeparator()
.addItem('Build Weekly Queue','buildWeeklyQueue')
.addItem('Post Approved GMB Rows','postApprovedGMBRows').addToUi();}
function getSheet_(n){const sh=SpreadsheetApp.getActive().getSheetByName(n);if(!sh)throw new Error('Missing sheet: '+n);return sh;}
function getConfig_(){const sh=getSheet_(SHEETS.CONFIG);const vals=sh.getRange(3,1,sh.getLastRow()-2,2).getValues();const cfg={};vals.forEach(([k,v])=>{if(k)cfg[String(k).trim()]=v;});const props=PropertiesService.getScriptProperties().getProperties();Object.keys(props).forEach(k=>cfg[k]=props[k]);return cfg;}
function getPromptTemplate_(name){const sh=getSheet_(SHEETS.PROMPTS);const vals=sh.getDataRange().getValues();for(let i=2;i<vals.length;i++){if(vals[i][1]===name)return vals[i][5];}throw new Error('Prompt not found: '+name);}
function fillTemplate_(tpl,vars){return String(tpl).replace(/\{([^}]+)\}/g,(_,k)=>vars[String(k).trim()]??'');}
function extractOutputText_(json){if(json.output_text)return json.output_text;if(Array.isArray(json.output)){const chunks=[];json.output.forEach(item=>{if(Array.isArray(item.content)){item.content.forEach(c=>{if(c.text)chunks.push(c.text);});}});if(chunks.length)return chunks.join('\n').trim();}return JSON.stringify(json,null,2);}
function callOpenAI_(prompt){const cfg=getConfig_();const apiKey=cfg.OPENAI_API_KEY; if(!apiKey) throw new Error('Missing OPENAI_API_KEY'); const model=cfg.OPENAI_MODEL||'gpt-5.4'; const res=UrlFetchApp.fetch('https://api.openai.com/v1/responses',{method:'post',contentType:'application/json',headers:{Authorization:'Bearer '+apiKey},payload:JSON.stringify({model:model,input:prompt}),muteHttpExceptions:true}); const text=res.getContentText(); if(res.getResponseCode()<200||res.getResponseCode()>=300) throw new Error('OpenAI API error: '+text); return extractOutputText_(JSON.parse(text));}
function getSelectedRowContext_(sheetName){const sh=SpreadsheetApp.getActive().getActiveSheet();const row=sh.getActiveRange().getRow();if(sh.getName()!==sheetName) throw new Error('Select a row on sheet: '+sheetName); if(row<3) throw new Error('Select a data row.'); return {sh,row};}
function pipelineRowToObject_(row){const v=getSheet_(SHEETS.PIPELINE).getRange(row,1,1,31).getValues()[0]; return {row,projectId:v[0],owner:v[1],brand:v[2],niche:v[3],topic:v[4],contentType:v[5],priority:v[7],dueDate:v[9],currentStage:v[18],promptUsed:v[26],aiOutput:v[27],statusNote:v[29]};}
function calendarRowToObject_(row){const v=getSheet_(SHEETS.CALENDAR).getRange(row,1,1,20).getValues()[0]; return {row,calendarId:v[0],postDate:v[1],platform:v[2],contentType:v[3],sourceProjectId:v[4],topic:v[5],workflowStatus:v[6],generatedCopy:v[7],cta:v[8],destinationUrl:v[9],locationKeywords:v[10],approval:v[11],autoQueue:v[12],publishedUrl:v[13],owner:v[15],notes:v[16],publishToGbp:v[17],gbpTopicType:v[18],mediaUrl:v[19]};}
function generateBlogOutlineFromSelectedRow(){const {row}=getSelectedRowContext_(SHEETS.PIPELINE);const item=pipelineRowToObject_(row);const cfg=getConfig_();const prompt=fillTemplate_(getPromptTemplate_('Blog Outline Builder'),{brand:item.brand||cfg.BRAND_NAME||'',topic:item.topic||'',niche:item.niche||'',cta:cfg.DEFAULT_CTA||'Learn more'})+'\n\nBrand voice: '+(cfg.BRAND_VOICE||'');const output=callOpenAI_(prompt);const sh=getSheet_(SHEETS.PIPELINE);sh.getRange(row,28).setValue(output);sh.getRange(row,27).setValue('Blog Outline Builder');sh.getRange(row,31).setValue(new Date());}
function generateSocialPackFromSelectedRow(){const {row}=getSelectedRowContext_(SHEETS.PIPELINE);const item=pipelineRowToObject_(row);const cfg=getConfig_();const prompt=fillTemplate_(getPromptTemplate_('Social Repurpose Pack'),{brand:item.brand||cfg.BRAND_NAME||'',topic:item.topic||'',cta:cfg.DEFAULT_CTA||'Learn more'})+'\n\nBrand voice: '+(cfg.BRAND_VOICE||'');const output=callOpenAI_(prompt);const sh=getSheet_(SHEETS.PIPELINE);sh.getRange(row,28).setValue(output);sh.getRange(row,27).setValue('Social Repurpose Pack');sh.getRange(row,31).setValue(new Date());}
function generateGMBPostFromSelectedRow(){const {row}=getSelectedRowContext_(SHEETS.CALENDAR);const item=calendarRowToObject_(row);const cfg=getConfig_();const prompt=fillTemplate_(getPromptTemplate_('GBP Post Generator'),{brand:cfg.BRAND_NAME||'',topic:item.topic||'',location_keywords:item.locationKeywords||cfg.DEFAULT_LOCATION_KEYWORDS||'',cta:item.cta||cfg.DEFAULT_CTA||'',url:item.destinationUrl||cfg.WEBSITE_URL||''})+'\n\nBrand voice: '+(cfg.BRAND_VOICE||'');const output=callOpenAI_(prompt);const sh=getSheet_(SHEETS.CALENDAR);sh.getRange(row,8).setValue(output);sh.getRange(row,7).setValue('Generated');}
function syncPipelineToCalendar(){const pipeline=getSheet_(SHEETS.PIPELINE),calendar=getSheet_(SHEETS.CALENDAR),cfg=getConfig_();const existing=new Set(calendar.getRange(3,5,Math.max(calendar.getLastRow()-2,1),1).getValues().flat().filter(String));const rows=pipeline.getRange(3,1,Math.max(pipeline.getLastRow()-2,1),31).getValues();let nextRow=Math.max(calendar.getLastRow()+1,3);rows.forEach(r=>{const id=r[0];if(!id||existing.has(id))return;const isGbp=r[5]==='Google Business Profile';calendar.getRange(nextRow,1,1,20).setValues([['CAL-'+Utilities.formatString('%03d',nextRow-2),r[9]||'',isGbp?'Google Business Profile':(r[5]==='Blog'?'Blog':r[5]),isGbp?'Update':r[5],id,r[4],'Planned','',cfg.DEFAULT_CTA||'Learn more',cfg.WEBSITE_URL||'',cfg.DEFAULT_LOCATION_KEYWORDS||'','Pending','Yes','','',r[1],(r[2]||'')+' | '+(r[29]||''),isGbp?'Yes':'No','STANDARD','']]);nextRow++;});}
function refreshKanbanBoard(){const rows=getSheet_(SHEETS.PIPELINE).getRange(3,1,Math.max(getSheet_(SHEETS.PIPELINE).getLastRow()-2,1),31).getValues();const board=getSheet_(SHEETS.KANBAN);const lanes=[{name:'Backlog',col:1},{name:'Research',col:4},{name:'Drafting',col:7},{name:'Editing',col:10},{name:'Design',col:13},{name:'Scheduled',col:16},{name:'Published',col:19},{name:'Distributed',col:22}];lanes.forEach(l=>board.getRange(6,l.col,15,2).clearContent());const grouped={};lanes.forEach(l=>grouped[l.name]=[]);rows.forEach(r=>{const stage=r[18]||'Backlog';if(grouped[stage])grouped[stage].push({id:r[0],topic:r[4],priority:r[7],due:r[9]});});const prio={High:1,Medium:2,Low:3};Object.keys(grouped).forEach(k=>grouped[k].sort((a,b)=>(prio[a.priority]||9)-(prio[b.priority]||9)));lanes.forEach(l=>grouped[l.name].slice(0,15).forEach((item,i)=>board.getRange(6+i,l.col).setValue([item.id,item.topic,item.priority?('Priority: '+item.priority):'',item.due?('Due: '+Utilities.formatDate(new Date(item.due),Session.getScriptTimeZone(),'yyyy-MM-dd')):''].filter(String).join('\n')).setWrap(true))); }
function buildWeeklyQueue(){const pipeline=getSheet_(SHEETS.PIPELINE),calendar=getSheet_(SHEETS.CALENDAR),cfg=getConfig_();const rows=pipeline.getRange(3,1,Math.max(pipeline.getLastRow()-2,1),31).getValues();const existing=new Set(calendar.getRange(3,5,Math.max(calendar.getLastRow()-2,1),1).getValues().flat().filter(String));const prio={High:1,Medium:2,Low:3};const backlog=rows.filter(r=>r[0]&&!existing.has(r[0])&&['Backlog','Research','Drafting'].includes(r[18]||'Backlog')).sort((a,b)=>(prio[a[7]]||9)-(prio[b[7]]||9)).slice(0,10);let nextRow=Math.max(calendar.getLastRow()+1,3),today=new Date();backlog.forEach((r,i)=>{const d=new Date(today);d.setDate(today.getDate()+i+1);const isGbp=r[5]==='Google Business Profile';calendar.getRange(nextRow,1,1,20).setValues([['CAL-'+Utilities.formatString('%03d',nextRow-2),d,isGbp?'Google Business Profile':(r[5]==='Blog'?'Blog':r[5]),isGbp?'Update':r[5],r[0],r[4],'Planned','',cfg.DEFAULT_CTA||'Learn more',cfg.WEBSITE_URL||'',cfg.DEFAULT_LOCATION_KEYWORDS||'','Pending','Yes','','',r[1],(r[2]||'')+' | '+(r[29]||''),isGbp?'Yes':'No','STANDARD','']]);nextRow++;});}
function mapCtaToActionType_(cta){const c=String(cta||'').toUpperCase(); if(c.includes('BOOK')) return 'BOOK'; if(c.includes('ORDER')) return 'ORDER'; if(c.includes('SHOP')) return 'SHOP'; if(c.includes('SIGN')) return 'SIGN_UP'; if(c.includes('CALL')) return 'CALL'; return 'LEARN_MORE';}
function buildLocalPostPayload_(item,cfg){const payload={languageCode:'en-US',summary:String(item.generatedCopy||'').trim(),topicType:item.gbpTopicType||'STANDARD'}; if(!payload.summary) throw new Error('Generated Copy is blank for row '+item.row); if(item.destinationUrl){payload.callToAction={actionType:mapCtaToActionType_(item.cta||cfg.DEFAULT_CTA||'LEARN_MORE'),url:item.destinationUrl};} if(item.mediaUrl){payload.media=[{sourceUrl:item.mediaUrl}];} return payload;}
function postApprovedGMBRows(){const cfg=getConfig_(); if(String(cfg.GBP_DIRECT_POSTING||'No')!=='Yes') throw new Error('GBP_DIRECT_POSTING is not enabled in Config.'); if(!cfg.GMB_ACCOUNT_ID||!cfg.GMB_LOCATION_ID) throw new Error('Missing GMB_ACCOUNT_ID or GMB_LOCATION_ID.'); const sh=getSheet_(SHEETS.CALENDAR); const rows=sh.getRange(3,1,Math.max(sh.getLastRow()-2,1),20).getValues(); const parent=cfg.GMB_ACCOUNT_ID+'/'+cfg.GMB_LOCATION_ID; const url='https://mybusiness.googleapis.com/v4/'+parent+'/localPosts'; const token=ScriptApp.getOAuthToken(); rows.forEach((_,idx)=>{const row=idx+3;const item=calendarRowToObject_(row); if(item.platform==='Google Business Profile'&&item.approval==='Approved'&&item.publishToGbp==='Yes'&&item.workflowStatus!=='Published'){const res=UrlFetchApp.fetch(url,{method:'post',contentType:'application/json',headers:{Authorization:'Bearer '+token},payload:JSON.stringify(buildLocalPostPayload_(item,cfg)),muteHttpExceptions:true}); if(res.getResponseCode()>=200&&res.getResponseCode()<300){const json=JSON.parse(res.getContentText()); sh.getRange(row,14).setValue(json.searchUrl||''); sh.getRange(row,7).setValue('Published');} else {sh.getRange(row,17).setValue('GBP ERROR '+res.getResponseCode()+': '+res.getContentText());}}});}
